export const productConstants = {
  Men: {
    Tops: ["T-shirt", "Tank top", "Croptop"],
    Bottoms: ["pants", "jeans", "shorts"],
    Jackets: ["Leather Jacket", "Jean Jacket", "Flight Jacket"],
    Shoes: ["Athletic shoes", "Sandals", "Boots"],
    Accessories: ["Hats", "Bells", "Sunglasses"],
    Sale: ["T-shirt", "Tank top", "Croptop"],
  },
  Ladies: {
    Tops: ["T-shirt", "Tank top", "Croptop"],
    Bottoms: ["pants", "jeans", "shorts"],
    Dresses: [
      "Rompers / Jumpsuits",
      "Casual dresses",
      "Going out dresses",
      "Party / Ocassion dresses",
      "Mini dresses",
      "Maxi / Midi dresses",
      "Sets",
    ],
    Jackets: ["Leather Jacket", "Jean Jacket", "Flight Jacket"],
    Shoes: ["Athletic shoes", "Sandals", "Boots"],
    Accessories: ["Hats", "Bells", "Sunglasses"],
    Sale: ["T-shirt", "Tank top", "Croptop"],
  },
  Girls: {
    Tops: ["T-shirt", "Tank top", "Croptop"],
    Bottoms: ["pants", "jeans", "sorts"],
    Dresses: [
        "Rompers / Jumpsuits",
        "Casual dresses",
        "Going out dresses",
        "Party / Ocassion dresses",
        "Mini dresses",
        "Maxi / Midi dresses",
        "Sets",
      ],
    Jackets: ["Leather Jacket", "Jean Jacket", "Flight Jacket"],
    Shoes: ["Athletic shoes", "Sandals", "Boots"],
    Accessories: ["Hats", "Bells", "Sunglasses"],
    Sale: ["T-shirt", "Tank top", "Croptop"],
  },
  Boys: {
    Tops: ["T-shirt", "Tank top", "Croptop"],
    Bottoms: ["pants", "jeans", "shorts"],
    Jackets: ["Leather Jacket", "Jean Jacket", "Flight Jacket"],
    Shoes: ["Athletic shoes", "Sandals", "Boots"],
    Accessories: ["Hats", "Bells", "Sunglasses"],
    Sale: ["T-shirt", "Tank top", "Croptop"],
  },
};
